<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412195208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('DROP TABLE article_conseille');
        $this->addSql('DROP TABLE candidature');
        $this->addSql('DROP TABLE cours');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_sponsor');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE inscription_formation');
        $this->addSql('DROP TABLE logs');
        $this->addSql('DROP TABLE merge_log');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE offre_emploi');
        $this->addSql('DROP TABLE parent_uploads');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE pidev_cours_user');
        $this->addSql('DROP TABLE reclamation');
        $this->addSql('DROP TABLE reunion');
        $this->addSql('DROP TABLE sponsor');
        $this->addSql('DROP TABLE suivie');
        $this->addSql('DROP TABLE therapie');
        $this->addSql('DROP TABLE todo');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP INDEX idx_emploi_jour ON emploi_du_temps');
        $this->addSql('DROP INDEX idx_emploi_tranche ON emploi_du_temps');
        $this->addSql('DROP INDEX id_rdv ON emploi_du_temps');
        $this->addSql('DROP INDEX idx_emploi_annee ON emploi_du_temps');
        $this->addSql('DROP INDEX id_seance ON emploi_du_temps');
        $this->addSql('ALTER TABLE emploi_du_temps CHANGE annee_scolaire annee_scolaire VARCHAR(20) NOT NULL, CHANGE jour_semaine jour_semaine VARCHAR(20) NOT NULL, CHANGE tranche_horaire tranche_horaire VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_rdv_autiste ON rdv');
        $this->addSql('DROP INDEX idx_rdv_statut ON rdv');
        $this->addSql('DROP INDEX idx_rdv_type ON rdv');
        $this->addSql('DROP INDEX idx_rdv_date ON rdv');
        $this->addSql('DROP INDEX idx_rdv_psychologue ON rdv');
        $this->addSql('ALTER TABLE rdv ADD zoom_join_url VARCHAR(255) DEFAULT NULL, ADD zoom_start_url LONGTEXT DEFAULT NULL, CHANGE type_consultation type_consultation VARCHAR(50) NOT NULL, CHANGE statut_rdv statut_rdv VARCHAR(20) DEFAULT \'planifiee\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_seance_professeur ON seance');
        $this->addSql('DROP INDEX idx_seance_date ON seance');
        $this->addSql('DROP INDEX idx_seance_jour ON seance');
        $this->addSql('DROP INDEX idx_seance_autiste ON seance');
        $this->addSql('DROP INDEX idx_seance_statut ON seance');
        $this->addSql('ALTER TABLE seance ADD zoom_join_url VARCHAR(255) DEFAULT NULL, ADD zoom_start_url LONGTEXT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE duree duree INT NOT NULL, CHANGE statut_seance statut_seance VARCHAR(20) DEFAULT \'planifiee\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article_conseille (id_article INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, contenu TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, Auteur VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, likes_count INT DEFAULT 0 NOT NULL, auteur_image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_article)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE candidature (id INT AUTO_INCREMENT NOT NULL, date_depot DATE NOT NULL, statut VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, disponibilite VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, score DOUBLE PRECISION NOT NULL, cv VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, offre_id INT NOT NULL, INDEX fk_candidature_offre (offre_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cours (id_cours INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type_cours TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, niveau VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, duree INT NOT NULL, image VARCHAR(225) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, mots TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, images_mots TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_cours)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation (id_eval INT AUTO_INCREMENT NOT NULL, id_cours INT NOT NULL, question TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix1 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix2 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix3 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, bonne_reponse VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, score INT DEFAULT 1 NOT NULL, INDEX id_cours (id_cours), PRIMARY KEY (id_eval)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE event (idEvent INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, typeEvent VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, lieu VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, maxParticipant INT NOT NULL, dateDebut DATE NOT NULL, dateFin DATE NOT NULL, heureDebut TIME NOT NULL, heureFin TIME NOT NULL, image VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, Planning TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (idEvent)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE event_sponsor (idEvent INT NOT NULL, idSponsor INT NOT NULL, INDEX idSponsor (idSponsor), PRIMARY KEY (idEvent, idSponsor)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE formation (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, duree INT NOT NULL, niveau VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_debut DATE DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE inscription_formation (id INT AUTO_INCREMENT NOT NULL, idFormation INT NOT NULL, disponibilite VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, mode_presence VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_inscrit DATE NOT NULL, status VARCHAR(30) CHARACTER SET utf8mb4 DEFAULT \'En attente\' COLLATE `utf8mb4_general_ci`, motivation TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX idFormation (idFormation), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE logs (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, user_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, action VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, details TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_logs_user (user_id), INDEX idx_logs_action (action), INDEX idx_logs_date (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE merge_log (id INT AUTO_INCREMENT NOT NULL, primary_user_id INT DEFAULT NULL, merged_user_id INT DEFAULT NULL, merge_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, fields_merged TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX primary_user_id (primary_user_id), INDEX merged_user_id (merged_user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type ENUM(\'info\', \'success\', \'warning\', \'error\') CHARACTER SET utf8mb4 DEFAULT \'info\' COLLATE `utf8mb4_general_ci`, is_read TINYINT DEFAULT 0, link VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_notifications_date (created_at), INDEX idx_notifications_user (user_id, is_read), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE offre_emploi (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, type_contrat VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, salaire NUMERIC(10, 2) DEFAULT NULL, date_publication DATE NOT NULL, date_expiration DATE NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE parent_uploads (ID_UPLOAD INT AUTO_INCREMENT NOT NULL, ID_SUIVIE INT NOT NULL, EMAIL_PARENT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, NOM_ENFANT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, SUBJECT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, FILE_NAME VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, FILE_PATH VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, UPLOADED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, SEEN TINYINT DEFAULT 0, INDEX fk_upload_suivie (ID_SUIVIE), PRIMARY KEY (ID_UPLOAD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE participation (id_participation INT AUTO_INCREMENT NOT NULL, id_user INT DEFAULT NULL, id_event INT NOT NULL, date_participation DATETIME DEFAULT CURRENT_TIMESTAMP, nbrP INT DEFAULT 1 NOT NULL, statut VARCHAR(50) CHARACTER SET utf8 DEFAULT \'confirmé\' COLLATE `utf8_general_ci`, UNIQUE INDEX unique_user_event (id_user, id_event), PRIMARY KEY (id_participation)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pidev_cours_user (id INT AUTO_INCREMENT NOT NULL, id_cours INT NOT NULL, id_user INT NOT NULL, date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, progression INT DEFAULT 0, statut ENUM(\'inscrit\', \'en_cours\', \'termine\') CHARACTER SET utf8mb4 DEFAULT \'inscrit\' COLLATE `utf8mb4_general_ci`, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, note INT DEFAULT NULL, INDEX idx_cours (id_cours), INDEX idx_user (id_user), UNIQUE INDEX unique_cours_user (id_cours, id_user), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reclamation (id INT AUTO_INCREMENT NOT NULL, date_creation DATE NOT NULL, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'En attente\' NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type_priorite VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Fiable, Medium, Critique\', demandeur VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_incident DATE DEFAULT NULL, assignee VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, delai_reponse INT DEFAULT NULL, demande TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, pieces_jointes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reunion (id INT AUTO_INCREMENT NOT NULL, id_reclamation INT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_reunion DATE NOT NULL, heure_debut TIME NOT NULL, heure_fin TIME DEFAULT NULL, duree_minutes INT DEFAULT NULL, type_reunion VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Online, On-site\', lieu VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Salle ou lien visio\', membres TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Liste des participants séparés par virgule\', ordre_jour TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, notes TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'Planifiée\' NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'Planifiée, En cours, Terminée, Annulée\', date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX id_reclamation (id_reclamation), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE sponsor (idSponsor INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, telephone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, TypeSponsor VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (idSponsor)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE suivie (ID_SUIVIE INT AUTO_INCREMENT NOT NULL, NOM_ENFANT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, EMAIL_PARENT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, AGE INT NOT NULL, NOM_PSY VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DATE_SUIVIE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, SCORE_HUMEUR INT NOT NULL, SCORE_STRESS INT NOT NULL, SCORE_ATTENTION INT NOT NULL, NIVEAU_SEANCE INT DEFAULT NULL, COMPORTEMENT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INTERACTION_SOCIALE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, OBSERVATION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, STATUT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, ID_THERAPIE_RECO INT DEFAULT NULL, CR_RESUME TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, CR_PDF_PATH VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PARENT_PDF_PATH VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PARENT_PDF_NAME VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PARENT_PDF_SUBJECT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PARENT_PDF_UPLOADED_AT DATETIME DEFAULT CURRENT_TIMESTAMP, PARENT_PDF_SEEN TINYINT DEFAULT 0 NOT NULL, INDEX fk_suivie_therapie (ID_THERAPIE_RECO), PRIMARY KEY (ID_SUIVIE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE therapie (ID_THERAPIE INT AUTO_INCREMENT NOT NULL, NOM_EXERCICE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, TYPE_EXERCICE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, OBJECTIF VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DESCRIPTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DUREE_MIN INT NOT NULL, MATERIEL VARCHAR(2550) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, ADAPTATION_TSA VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, CIBLE VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_HUMEUR VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_ATTENTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_STRESSE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, COMPORTEMENT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INTERACTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAU INT NOT NULL, PRIMARY KEY (ID_THERAPIE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE todo (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_echeance DATE DEFAULT NULL, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'EN_COURS\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, prenom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, password VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, role ENUM(\'admin\', \'user\', \'professeur\', \'psychologue\', \'enfant\', \'parent\') CHARACTER SET utf8mb4 DEFAULT \'user\' COLLATE `utf8mb4_general_ci`, otp_code VARCHAR(6) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, image_path VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, phone VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, status ENUM(\'active\', \'merged\', \'deactivated\') CHARACTER SET utf8mb4 DEFAULT \'active\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, otp_expiry DATETIME DEFAULT NULL, UNIQUE INDEX email (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE emploi_du_temps CHANGE annee_scolaire annee_scolaire VARCHAR(20) NOT NULL COMMENT \'e.g., 2024-2025\', CHANGE jour_semaine jour_semaine ENUM(\'lundi\', \'mardi\', \'mercredi\', \'jeudi\', \'vendredi\', \'samedi\', \'dimanche\') NOT NULL, CHANGE tranche_horaire tranche_horaire ENUM(\'matin\', \'apres_midi\', \'soir\', \'journee\') NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_emploi_jour ON emploi_du_temps (jour_semaine)');
        $this->addSql('CREATE INDEX idx_emploi_tranche ON emploi_du_temps (tranche_horaire)');
        $this->addSql('CREATE INDEX id_rdv ON emploi_du_temps (id_rdv)');
        $this->addSql('CREATE INDEX idx_emploi_annee ON emploi_du_temps (annee_scolaire)');
        $this->addSql('CREATE INDEX id_seance ON emploi_du_temps (id_seance)');
        $this->addSql('ALTER TABLE rdv DROP zoom_join_url, DROP zoom_start_url, CHANGE type_consultation type_consultation ENUM(\'premiere_consultation\', \'suivi\', \'urgence\', \'familiale\', \'bilan\') NOT NULL, CHANGE statut_rdv statut_rdv ENUM(\'planifiee\', \'confirme\', \'annule\', \'reporte\', \'termine\') DEFAULT \'planifiee\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_rdv_autiste ON rdv (id_autiste)');
        $this->addSql('CREATE INDEX idx_rdv_statut ON rdv (statut_rdv)');
        $this->addSql('CREATE INDEX idx_rdv_type ON rdv (type_consultation)');
        $this->addSql('CREATE INDEX idx_rdv_date ON rdv (date_heure_rdv)');
        $this->addSql('CREATE INDEX idx_rdv_psychologue ON rdv (id_psychologue)');
        $this->addSql('ALTER TABLE seance DROP zoom_join_url, DROP zoom_start_url, CHANGE description description TEXT DEFAULT NULL, CHANGE duree duree INT NOT NULL COMMENT \'Duration in minutes\', CHANGE statut_seance statut_seance ENUM(\'planifiee\', \'confirme\', \'annule\', \'reporte\', \'termine\') DEFAULT \'planifiee\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_seance_professeur ON seance (id_professeur)');
        $this->addSql('CREATE INDEX idx_seance_date ON seance (date_seance)');
        $this->addSql('CREATE INDEX idx_seance_jour ON seance (jours_semaine)');
        $this->addSql('CREATE INDEX idx_seance_autiste ON seance (id_autiste)');
        $this->addSql('CREATE INDEX idx_seance_statut ON seance (statut_seance)');
    }
}
