<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408001439 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE multiplayer_event (id INT AUTO_INCREMENT NOT NULL, game_code VARCHAR(255) NOT NULL, player1_id INT NOT NULL, player2_id INT DEFAULT NULL, player1_score INT NOT NULL, player2_score INT NOT NULL, current_challenge INT NOT NULL, status VARCHAR(20) DEFAULT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE emploi_du_temps DROP FOREIGN KEY `emploi_du_temps_ibfk_1`');
        $this->addSql('ALTER TABLE emploi_du_temps DROP FOREIGN KEY `emploi_du_temps_ibfk_2`');
        $this->addSql('DROP TABLE article_conseille');
        $this->addSql('DROP TABLE cours');
        $this->addSql('DROP TABLE emploi_du_temps');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE logs');
        $this->addSql('DROP TABLE merge_log');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE parent_uploads');
        $this->addSql('DROP TABLE pidev_cours_user');
        $this->addSql('DROP TABLE rdv');
        $this->addSql('DROP TABLE seance');
        $this->addSql('DROP TABLE suivie');
        $this->addSql('DROP TABLE therapie');
        $this->addSql('DROP TABLE todo');
        $this->addSql('DROP TABLE user');
        $this->addSql('ALTER TABLE event CHANGE description description LONGTEXT NOT NULL, CHANGE dateFin dateFin DATE DEFAULT NULL, CHANGE heureFin heureFin TIME DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article_conseille (id_article INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, contenu TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, categorie VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, Auteur VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, likes_count INT DEFAULT 0 NOT NULL, auteur_image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_article)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE cours (id_cours INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type_cours TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, niveau VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, duree INT NOT NULL, image VARCHAR(225) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, mots TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, images_mots TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_cours)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE emploi_du_temps (id_emploi INT AUTO_INCREMENT NOT NULL, annee_scolaire VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'e.g., 2024-2025\', jour_semaine ENUM(\'lundi\', \'mardi\', \'mercredi\', \'jeudi\', \'vendredi\', \'samedi\', \'dimanche\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, tranche_horaire ENUM(\'matin\', \'apres_midi\', \'soir\', \'journee\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, id_rdv INT DEFAULT NULL, id_seance INT DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_emploi_tranche (tranche_horaire), INDEX id_rdv (id_rdv), INDEX idx_emploi_annee (annee_scolaire), INDEX id_seance (id_seance), INDEX idx_emploi_jour (jour_semaine), PRIMARY KEY (id_emploi)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE evaluation (id_eval INT AUTO_INCREMENT NOT NULL, id_cours INT NOT NULL, question TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix1 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix2 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, choix3 VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, bonne_reponse VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, score INT DEFAULT 1 NOT NULL, INDEX id_cours (id_cours), PRIMARY KEY (id_eval)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE logs (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, user_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, action VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, details TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_logs_user (user_id), INDEX idx_logs_action (action), INDEX idx_logs_date (created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE merge_log (id INT AUTO_INCREMENT NOT NULL, primary_user_id INT DEFAULT NULL, merged_user_id INT DEFAULT NULL, merge_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, fields_merged TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX primary_user_id (primary_user_id), INDEX merged_user_id (merged_user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, type ENUM(\'info\', \'success\', \'warning\', \'error\') CHARACTER SET utf8mb4 DEFAULT \'info\' COLLATE `utf8mb4_general_ci`, is_read TINYINT DEFAULT 0, link VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_notifications_date (created_at), INDEX idx_notifications_user (user_id, is_read), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE parent_uploads (ID_UPLOAD INT AUTO_INCREMENT NOT NULL, ID_SUIVIE INT NOT NULL, EMAIL_PARENT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, NOM_ENFANT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, SUBJECT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, FILE_NAME VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, FILE_PATH VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, UPLOADED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, SEEN TINYINT DEFAULT 0, INDEX fk_upload_suivie (ID_SUIVIE), PRIMARY KEY (ID_UPLOAD)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pidev_cours_user (id INT AUTO_INCREMENT NOT NULL, id_cours INT NOT NULL, id_user INT NOT NULL, date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, progression INT DEFAULT 0, statut ENUM(\'inscrit\', \'en_cours\', \'termine\') CHARACTER SET utf8mb4 DEFAULT \'inscrit\' COLLATE `utf8mb4_general_ci`, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, note INT DEFAULT NULL, INDEX idx_cours (id_cours), INDEX idx_user (id_user), UNIQUE INDEX unique_cours_user (id_cours, id_user), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rdv (id_rdv INT AUTO_INCREMENT NOT NULL, type_consultation ENUM(\'premiere_consultation\', \'suivi\', \'urgence\', \'familiale\', \'bilan\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, date_heure_rdv DATETIME NOT NULL, statut_rdv ENUM(\'planifiee\', \'confirme\', \'annule\', \'reporte\', \'termine\') CHARACTER SET utf8mb4 DEFAULT \'planifiee\' COLLATE `utf8mb4_unicode_ci`, duree_rdv_minutes INT NOT NULL, id_psychologue INT NOT NULL, id_autiste INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_rdv_autiste (id_autiste), INDEX idx_rdv_statut (statut_rdv), INDEX idx_rdv_type (type_consultation), INDEX idx_rdv_date (date_heure_rdv), INDEX idx_rdv_psychologue (id_psychologue), PRIMARY KEY (id_rdv)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE seance (id_seance INT AUTO_INCREMENT NOT NULL, titre_seance VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_seance DATETIME NOT NULL, jours_semaine VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, duree INT NOT NULL COMMENT \'Duration in minutes\', statut_seance ENUM(\'planifiee\', \'confirme\', \'annule\', \'reporte\', \'termine\') CHARACTER SET utf8mb4 DEFAULT \'planifiee\' COLLATE `utf8mb4_unicode_ci`, id_autiste INT NOT NULL, id_professeur INT NOT NULL, id_cours INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_seance_autiste (id_autiste), INDEX idx_seance_statut (statut_seance), INDEX idx_seance_professeur (id_professeur), INDEX idx_seance_date (date_seance), INDEX idx_seance_jour (jours_semaine), PRIMARY KEY (id_seance)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE suivie (ID_SUIVIE INT AUTO_INCREMENT NOT NULL, NOM_ENFANT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, EMAIL_PARENT VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, AGE INT NOT NULL, NOM_PSY VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DATE_SUIVIE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, SCORE_HUMEUR INT NOT NULL, SCORE_STRESS INT NOT NULL, SCORE_ATTENTION INT NOT NULL, NIVEAU_SEANCE INT DEFAULT NULL, COMPORTEMENT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INTERACTION_SOCIALE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, OBSERVATION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, STATUT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, ID_THERAPIE_RECO INT DEFAULT NULL, CR_RESUME TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, CR_PDF_PATH VARCHAR(500) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PARENT_PDF_UPLOADED_AT DATETIME DEFAULT CURRENT_TIMESTAMP, PARENT_PDF_SEEN TINYINT DEFAULT 0 NOT NULL, INDEX fk_suivie_therapie (ID_THERAPIE_RECO), PRIMARY KEY (ID_SUIVIE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE therapie (ID_THERAPIE INT AUTO_INCREMENT NOT NULL, NOM_EXERCICE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, TYPE_EXERCICE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, OBJECTIF VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DESCRIPTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, DUREE_MIN INT NOT NULL, MATERIEL VARCHAR(2550) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, ADAPTATION_TSA VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, CIBLE VARCHAR(30) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_HUMEUR VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_ATTENTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAUX_STRESSE VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, COMPORTEMENT VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INTERACTION VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, NIVEAU INT NOT NULL, PRIMARY KEY (ID_THERAPIE)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE todo (id INT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_echeance DATE DEFAULT NULL, statut VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'EN_COURS\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user (id INT NOT NULL, nom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, prenom VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, password VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, role ENUM(\'admin\', \'user\', \'professeur\', \'psychologue\', \'enfant\', \'parent\') CHARACTER SET utf8mb4 DEFAULT \'user\' COLLATE `utf8mb4_general_ci`, otp_code VARCHAR(6) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, image_path VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, phone VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, status ENUM(\'active\', \'merged\', \'deactivated\') CHARACTER SET utf8mb4 DEFAULT \'active\' COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, otp_expiry DATETIME DEFAULT NULL, UNIQUE INDEX email (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE emploi_du_temps ADD CONSTRAINT `emploi_du_temps_ibfk_1` FOREIGN KEY (id_rdv) REFERENCES rdv (id_rdv) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE emploi_du_temps ADD CONSTRAINT `emploi_du_temps_ibfk_2` FOREIGN KEY (id_seance) REFERENCES seance (id_seance) ON DELETE CASCADE');
        $this->addSql('DROP TABLE multiplayer_event');
        $this->addSql('ALTER TABLE event CHANGE description description VARCHAR(255) NOT NULL, CHANGE dateFin dateFin DATE NOT NULL, CHANGE heureFin heureFin TIME NOT NULL');
    }
}
